<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__User__CLASSMETADATA__' => 0,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'fullname' => $o[2],
                        'email' => $o[3],
                        'phone' => $o[4],
                        'birth' => $o[5],
                        'address' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'fullname' => 'fullname',
                        'email' => 'email',
                        'phone' => 'phone',
                        'birth' => 'birth',
                        'address' => 'address',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'fullname' => 'fullname',
                        'email' => 'email',
                        'phone' => 'phone',
                        'birth' => 'birth',
                        'address' => 'address',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                        'quoted' => true,
                    ],
                ],
                'idGenerator' => [
                    $o[7],
                ],
                'name' => [
                    'App\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'date',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'fullname',
                    'email',
                    'phone',
                    'birth',
                    'address',
                ],
                'columnName' => [
                    1 => 'id',
                    'fullname',
                    'email',
                    'phone',
                    'birth',
                    'address',
                ],
                'length' => [
                    2 => 100,
                    150,
                    20,
                    6 => 255,
                ],
                'nullable' => [
                    4 => true,
                    true,
                    true,
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
