<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtx8prw\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtx8prw/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLtx8prw.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLtx8prw\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLtx8prw\App_KernelProdContainer([
    'container.build_hash' => 'Ltx8prw',
    'container.build_id' => '57f1a4ce',
    'container.build_time' => 1754508362,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtx8prw');
