<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'ynote_form' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/']], [], [], []],
    'ynote_save' => [[], ['_controller' => 'App\\Controller\\UserController::save'], [], [['text', '/submit']], [], [], []],
    'App\Controller\UserController::index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\UserController::save' => [[], ['_controller' => 'App\\Controller\\UserController::save'], [], [['text', '/submit']], [], [], []],
];
