<?php

namespace ContainerPpRRTNj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllersaveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BaqA9Ui.App\Controller\UserController::save()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BaqA9Ui.App\\Controller\\UserController::save()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'csrfTokenManager' => ['privates', 'security.csrf.same_origin_token_manager', 'getSecurity_Csrf_SameOriginTokenManagerService', false],
        ], [
            'validator' => '?',
            'csrfTokenManager' => '?',
        ]))->withContext('App\\Controller\\UserController::save()', $container);
    }
}
