<?php

namespace ContainerLtx8prw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.nFP4C...App\Controller\UserController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nFP4C...App\\Controller\\UserController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.same_origin_token_manager', 'getSecurity_Csrf_SameOriginTokenManagerService', false],
        ], [
            'csrfTokenManager' => '?',
        ]))->withContext('App\\Controller\\UserController::index()', $container);
    }
}
