<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1FvTm9x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1FvTm9x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1FvTm9x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1FvTm9x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1FvTm9x\App_KernelDevDebugContainer([
    'container.build_hash' => '1FvTm9x',
    'container.build_id' => 'e8d6e6c6',
    'container.build_time' => 1754514712,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1FvTm9x');
