<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpRRTNj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpRRTNj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPpRRTNj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPpRRTNj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPpRRTNj\App_KernelDevDebugContainer([
    'container.build_hash' => 'PpRRTNj',
    'container.build_id' => '53bfb052',
    'container.build_time' => 1754458599,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpRRTNj');
